networks:
  default:
    driver: bridge

services:
  marimo:
    build: .
    image: ai-providers:latest
    ports:
      - 8000:8000
    container_name: ai-providers-container
    networks:
      - default
    volumes:
      - ai-providers-volume:/app/storage
    restart: unless-stopped
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - XAI_API_KEY=${XAI_API_KEY}
      - BEDROCK_API_KEY=${BEDROCK_API_KEY}
      - META_API_KEY=${META_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      start_period: 30s
      interval: 30s
      retries: 5
      timeout: 3s

volumes:
  ai-providers-volume:
    name: ai-providers-volume